# Generated by Django 4.2.28 on 2026-02-27 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmplitudeSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.TimeField(default=datetime.time(1, 0))),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amplitude Sync Schedule',
                'verbose_name_plural': 'Amplitude Sync Schedules',
            },
        ),
        migrations.CreateModel(
            name='DailyDeviceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('visit_times', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('insert_id', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-event_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='dailydeviceactivity',
            constraint=models.UniqueConstraint(fields=('date', 'device_id'), name='uniq_daily_activity_per_device'),
        ),
    ]
