# Generated by Django 4.2.28 on 2026-02-27 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydeviceactivity',
            options={'ordering': ('-last_seen',), 'verbose_name': 'Дневная активность устройства', 'verbose_name_plural': 'Дневная активность устройств'},
        ),
        migrations.AlterModelOptions(
            name='mobilesession',
            options={'ordering': ('-event_time',), 'verbose_name': 'Сессия мобильного события', 'verbose_name_plural': 'Сессии мобильных событий'},
        ),
        migrations.AddField(
            model_name='dailydeviceactivity',
            name='device_brand',
            field=models.CharField(blank=True, max_length=128, verbose_name='Бренд устройства'),
        ),
        migrations.AddField(
            model_name='dailydeviceactivity',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Производитель устройства'),
        ),
        migrations.AddField(
            model_name='dailydeviceactivity',
            name='device_model',
            field=models.CharField(blank=True, max_length=128, verbose_name='Модель устройства'),
        ),
        migrations.AddField(
            model_name='mobilesession',
            name='device_brand',
            field=models.CharField(blank=True, max_length=128, verbose_name='Бренд устройства'),
        ),
        migrations.AddField(
            model_name='mobilesession',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Производитель устройства'),
        ),
        migrations.AddField(
            model_name='mobilesession',
            name='device_model',
            field=models.CharField(blank=True, max_length=128, verbose_name='Модель устройства'),
        ),
        migrations.AlterField(
            model_name='amplitudesyncschedule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='amplitudesyncschedule',
            name='last_run_on',
            field=models.DateField(blank=True, null=True, verbose_name='Последний запуск (дата)'),
        ),
        migrations.AlterField(
            model_name='amplitudesyncschedule',
            name='run_at',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='Время запуска'),
        ),
        migrations.AlterField(
            model_name='amplitudesyncschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ID устройства'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый визит'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний визит'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='platform',
            field=models.CharField(blank=True, max_length=64, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='visit_times',
            field=models.JSONField(blank=True, default=list, verbose_name='Времена визитов'),
        ),
        migrations.AlterField(
            model_name='dailydeviceactivity',
            name='visits_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество визитов'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='dedupe_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ключ дедупликации'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ID устройства'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='event_time',
            field=models.DateTimeField(db_index=True, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='insert_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Insert ID'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='platform',
            field=models.CharField(blank=True, max_length=64, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='raw_event',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырое событие'),
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID пользователя'),
        ),
    ]
