# Generated by Django 4.2.28 on 2026-02-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0002_alter_dailydeviceactivity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='Время визита')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='amplitude.dailydeviceactivity', verbose_name='Дневная активность')),
            ],
            options={
                'verbose_name': 'Время визита устройства',
                'verbose_name_plural': 'Времена визитов устройств',
                'ordering': ('event_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='devicevisittime',
            constraint=models.UniqueConstraint(fields=('daily_activity', 'event_time'), name='uniq_visit_time_per_activity'),
        ),
    ]
