# Generated by Django 4.2.28 on 2026-02-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0003_devicevisittime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydeviceactivity',
            name='visit_times',
        ),
    ]
