# Generated by Django 4.2.28 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0005_remove_amplitudesyncschedule_last_run_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigDataVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigdata_visit_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID визита BigData')),
                ('guest_phone_raw', models.CharField(blank=True, max_length=64, verbose_name='Телефон (raw)')),
                ('guest_phone_normalized', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Телефон (normalized)')),
                ('time_create', models.DateTimeField(db_index=True, verbose_name='Время визита')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ BigData')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Визит BigData',
                'verbose_name_plural': 'Визиты BigData',
                'ordering': ('-time_create',),
            },
        ),
        migrations.AddIndex(
            model_name='bigdatavisit',
            index=models.Index(fields=('guest_phone_normalized', 'time_create'), name='idx_bigdata_phone_time'),
        ),
    ]
