# Generated by Django 4.2.28 on 2026-04-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDispatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название купона для приложения')),
                ('marketing_sale_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID маркетинговой акции')),
                ('marketing_sale_name', models.CharField(blank=True, max_length=255, verbose_name='Название маркетинговой акции')),
                ('input_source', models.CharField(choices=[('manual', 'Ручной ввод'), ('excel', 'Excel файл'), ('mixed', 'Смешанный')], default='manual', max_length=16, verbose_name='Источник телефонов')),
                ('source_text', models.TextField(blank=True, verbose_name='Телефоны (ручной ввод)')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='coupon_dispatch/', verbose_name='Excel файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('total_phones', models.PositiveIntegerField(default=0, verbose_name='Телефонов в исходных данных')),
                ('unique_phones', models.PositiveIntegerField(default=0, verbose_name='Уникальных валидных телефонов')),
                ('guests_found', models.PositiveIntegerField(default=0, verbose_name='Найдено гостей')),
                ('available_coupons', models.PositiveIntegerField(default=0, verbose_name='Доступных купонов на старте')),
                ('coupons_assigned', models.PositiveIntegerField(default=0, verbose_name='Назначено купонов')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('mobile_api_sent', models.BooleanField(default=False, verbose_name='Отправлено в mobile API')),
                ('mobile_api_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки в mobile API')),
                ('mobile_api_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ mobile API')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_dispatch_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Задача рассылки купонов',
                'verbose_name_plural': 'Задачи рассылки купонов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponDispatchJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_raw', models.CharField(blank=True, max_length=64, verbose_name='Телефон (как введен)')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон (normalized)')),
                ('guest_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID гостя')),
                ('coupon_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID купона')),
                ('coupon_code', models.CharField(blank=True, max_length=128, verbose_name='Код купона')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Успех')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='coupon_dispatch.coupondispatchjob', verbose_name='Задача рассылки')),
            ],
            options={
                'verbose_name': 'Результат рассылки купона',
                'verbose_name_plural': 'Результаты рассылки купонов',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['job', 'success'], name='idx_coup_job_success')],
            },
        ),
    ]
