# Generated by Django 4.2.28 on 2026-03-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidBirthdayNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hb_kids', 'HB Kids')], max_length=32, verbose_name='Тип уведомления')),
                ('birthday_date', models.DateField(db_index=True, verbose_name='Дата дня рождения')),
                ('kid_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID ребенка')),
                ('kid_name', models.CharField(blank=True, max_length=255, verbose_name='Имя ребенка')),
                ('guest_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID гостя')),
                ('guest_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон гостя')),
                ('schedule_date', models.DateField(db_index=True, verbose_name='Дата отправки')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='Запланировано на')),
                ('sent', models.BooleanField(db_index=True, default=False, verbose_name='Уведомление отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('processing_started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Взято в обработку')),
                ('story_created', models.BooleanField(default=False, verbose_name='Story создан')),
                ('external_story_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID Story во внешнем API')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('kid_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw payload kid')),
                ('guest_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw payload guest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Очередь уведомления о ДР ребенка',
                'verbose_name_plural': 'Очередь уведомлений о ДР детей',
                'ordering': ('sent', 'scheduled_for', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hb_kids', 'HB Kids')], max_length=32, unique=True, verbose_name='Тип уведомления')),
                ('send_time', models.TimeField(verbose_name='Время отправки (Asia/Almaty)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Расписание уведомления',
                'verbose_name_plural': 'Расписания уведомлений',
                'ordering': ('notification_type',),
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hb_kids', 'HB Kids')], max_length=32, unique=True, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('body', models.TextField(verbose_name='Текст (RU)')),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (KZ)')),
                ('body_kz', models.TextField(blank=True, verbose_name='Текст (KZ)')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Город (опционально)')),
                ('park', models.CharField(blank=True, max_length=128, verbose_name='Парк (опционально)')),
                ('notification_backend_type', models.CharField(default='default', max_length=64, verbose_name='notification_type для mobile API')),
                ('survey_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='survey_id (опционально)')),
                ('review_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='review_id (опционально)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон push-уведомления',
                'verbose_name_plural': 'Шаблоны push-уведомлений',
                'ordering': ('notification_type',),
            },
        ),
        migrations.CreateModel(
            name='StoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hb_kids', 'HB Kids')], max_length=32, unique=True, verbose_name='Тип уведомления')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название Story (опционально)')),
                ('logo', models.FileField(upload_to='story_templates/logos/', verbose_name='Logo файл')),
                ('city', models.PositiveIntegerField(verbose_name='ID города')),
                ('story_type', models.CharField(default='DEFAULT', max_length=64, verbose_name='Story type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('start_offset_days', models.IntegerField(default=0, verbose_name='Смещение start_date (дней от сегодня)')),
                ('end_offset_days', models.IntegerField(default=14, verbose_name='Смещение end_date (дней от сегодня)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон Story',
                'verbose_name_plural': 'Шаблоны Story',
                'ordering': ('notification_type',),
            },
        ),
        migrations.CreateModel(
            name='StoryDisplayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('display_type', models.CharField(max_length=64, verbose_name='display_type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (опционально)')),
                ('text', models.TextField(blank=True, verbose_name='Текст (опционально)')),
                ('image', models.FileField(blank=True, null=True, upload_to='story_templates/displays/images/', verbose_name='Image файл')),
                ('video', models.FileField(blank=True, null=True, upload_to='story_templates/displays/videos/', verbose_name='Video файл')),
                ('park', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID парка (опционально)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка (опционально)')),
                ('season', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сезона (опционально)')),
                ('advertisement', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID рекламы (опционально)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('story_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_templates', to='notifications.storytemplate', verbose_name='Шаблон Story')),
            ],
            options={
                'verbose_name': 'Шаблон экрана Story',
                'verbose_name_plural': 'Шаблоны экранов Story',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='kidbirthdaynotification',
            constraint=models.UniqueConstraint(fields=('notification_type', 'schedule_date', 'kid_id'), name='uniq_kid_birthday_notification_once_per_day'),
        ),
    ]
